const crypto=require('node:crypto');
const text=v=>String(v??'').trim();
const money=v=>{if(typeof v==='number')return v;let s=text(v).replace(/[R$\s]/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return Number(s)||0};
const iso=v=>{const s=text(v),br=s.match(/^(\d{2})[/-](\d{2})[/-](\d{4})/);return br?`${br[3]}-${br[2]}-${br[1]}`:s.slice(0,10)};
const br=v=>{const s=iso(v);return /^\d{4}-\d{2}-\d{2}$/.test(s)?`${s.slice(8,10)}/${s.slice(5,7)}/${s.slice(0,4)}`:text(v)};
const stamp=v=>{const s=text(v),m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})(?:[ ,]+(\d{2}):(\d{2})(?::(\d{2}))?)?/);if(m)return Date.parse(`${m[3]}-${m[2]}-${m[1]}T${m[4]||'00'}:${m[5]||'00'}:${m[6]||'00'}-03:00`)||0;return Date.parse(s)||0};
const now=()=>new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',hour12:false});
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
const id=prefix=>`${prefix}-${new Date().toLocaleString('sv-SE',{timeZone:'America/Sao_Paulo'}).replace(/\D/g,'').slice(0,14)}-${crypto.randomInt(1000,10000)}`;
const hash=password=>crypto.createHash('sha256').update(String(password)).digest('hex');
const normal=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const cpfOk=v=>{const c=text(v).replace(/\D/g,'');if(c.length!==11||/^(\d)\1+$/.test(c))return false;for(let n=9;n<=10;n++){let d=(c.slice(0,n).split('').reduce((s,x,i)=>s+Number(x)*(n+1-i),0)*10)%11;if(d===10)d=0;if(d!==Number(c[n]))return false}return true};
const cpf=v=>text(v).replace(/\D/g,'').replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,'$1.$2.$3-$4');
const photos=v=>{if(Array.isArray(v))return v.filter(Boolean);try{return JSON.parse(v||'[]').filter(Boolean)}catch{return []}};
module.exports={text,money,iso,br,stamp,now,today,id,hash,normal,cpfOk,cpf,photos};
